***
 **Name:** Khalid Saifullah \
 **Student ID:** A20423546 \
 **Course:** CS577 \
 **Semester:** Spring 2021

In [11]:
import numpy as np

# Answer to the Question No. A

In [12]:
#Given

a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])
c = np.array([[-1], [1], [3]])

In [13]:
#Solutions

ansA1 = 2*a - b
ansA2 = a / np.linalg.norm(a)
ansA3a = np.linalg.norm(a)
ansA3b = np.arccos(a[0] / ansA3a)
ansA4 = a / ansA3a
ansA5 = np.arccos(np.dot(a.T,b)/(np.linalg.norm(a) * np.linalg.norm(b)))
ansA6a = np.dot(a.T,b)
ansA6b = np.dot(b.T,a)
ansA7 = np.linalg.norm(a) * np.linalg.norm(b) * np.cos(ansA5)
ansA8 = np.dot(b.T,ansA2)
ansA9 = np.cross(a.T,np.random.randint(5, size=np.size(a)))
ansA10a = np.cross(a.T,b.T)
ansA10b = np.cross(b.T,a.T)
ansA11 = np.cross(a.T,b.T)
ansA12 = np.linalg.lstsq(np.column_stack([a, b]), c, rcond=None)[0]
ansA13a = np.dot(a.T,b)
ansA13b = np.dot(a,b.T)

In [14]:
print('1.', ansA1, '\n')
print('2. The unit vector in the direction of a is \n', ansA2, '\n')
print('3. ||a|| is ', ansA3a, 'radians')
print('The angle of a relative to the positive x axis is ', ansA3b.item(0), 'radians. \n')
print('4. The direction cosines of a is\n', ansA4, '\n')
print('5. The angle between a and b is', ansA5.item(0), 'radians.\n')
print('6. a.b is ', ansA6a.item(0), 'and b.a is ', ansA6b.item(0), '\n')
print('7. a.b by using the angle between a and b is ', ansA7.item(0), '\n')
print('8. The scalar projection of b onto a^ is ', ansA8.item(0), '\n')
print('9. A vector which is perpendicular to a is ', ansA9, '\n')
print('10. a x b is ', ansA10a, 'and b x a is ', ansA10b, '\n')
print('11. A vector which is perpendicular to both a and b is ', ansA11, '\n')
print('12. The linear dependence of c on [a; b] is ', round(ansA12.item(0)), '*a', round(ansA12.item(1)), '*b\n')
print('13. aTb is ', ansA13a, 'and abT is ', ansA13b, '\n')

1. [[-2]
 [-1]
 [ 0]] 

2. The unit vector in the direction of a is 
 [[0.26726124]
 [0.53452248]
 [0.80178373]] 

3. ||a|| is  3.7416573867739413 radians
The angle of a relative to the positive x axis is  1.3002465638163236 radians. 

4. The direction cosines of a is
 [[0.26726124]
 [0.53452248]
 [0.80178373]] 

5. The angle between a and b is 0.2257261285527342 radians.

6. a.b is  32 and b.a is  32 

7. a.b by using the angle between a and b is  32.0 

8. The scalar projection of b onto a^ is  8.55235974119758 

9. A vector which is perpendicular to a is  [[-5  1  1]] 

10. a x b is  [[-3  6 -3]] and b x a is  [[ 3 -6  3]] 

11. A vector which is perpendicular to both a and b is  [[-3  6 -3]] 

12. The linear dependence of c on [a; b] is  3 *a -1 *b

13. aTb is  [[32]] and abT is  [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]] 



# Answer to the Question No. B

In [15]:
#Given

A = np.array([[1, 2, 3], [4, -2, 3], [0, 5, -1]])
B = np.array([[1, 2, 1], [2, 1, -4], [3, -2, 1]])
C = np.array([[1, 2, 3], [4, 5, 6], [-1, 1, 3]])
d = np.array([[1], [2], [3]])

In [16]:
#Solutions

ansB1 = 2*A-B
ansB2a = np.matmul(A,B)
ansB2b = np.matmul(B,A)
ansB3a = np.matmul(A,B).T
ansB3b = np.matmul(B.T,A.T)
ansB4a = np.linalg.det(A)
ansB4b = np.linalg.det(C)
ansB6a = np.linalg.inv(A)
ansB6b = np.linalg.inv(B)
ansB7 = np.linalg.inv(C)
ansB8 = np.matmul(A,d)
ansB9a = np.dot(A[0], d)
ansB9b = np.dot(A[1], d)
ansB9c = np.dot(A[2], d)
ansB10 = np.linalg.solve(A,d)
ansB11 = np.matrix.round(np.linalg.solve(B,d))
ansB12 = np.linalg.solve(C,d)

In [17]:
print('1.', ansB1, '\n')
print('2. AB is\n', ansB2a, '\n\n and BA is\n', ansB2b, '\n')
print('3. (AB)^T is\n', ansB3a,  '\n\n and B^T A^T is\n', ansB3b, '\n')
print('4. |A| is', round(ansB4a), 'and |B| is', round(ansB4b), '\n')
print('5. For two vectors to be orthogonal, their dot product has to be equal to 0.\n',
     'For matrix A, row1 (dot) row2 = ', np.dot(A[0,:],A[1,:]), '\n', 
     'row1 (dot) row3 = ', np.dot(A[0,:],A[2,:]), '\n', 
     'row2 (dot) row3 = ', np.dot(A[1,:],A[2,:]), '\n\n', 
     'For matrix B, row1 (dot) row2 = ', np.dot(B[0,:],B[1,:]), '\n', 
     'row1 (dot) row3 = ', np.dot(B[0,:],B[2,:]), '\n', 
     'row2 (dot) row3 = ', np.dot(B[1,:],B[2,:]), '\n\n', 
     'For matrix C, row1 (dot) row2 = ', np.dot(C[0,:],C[1,:]), '\n', 
     'row1 (dot) row3 = ', np.dot(C[0,:],C[2,:]), '\n', 
     'row2 (dot) row3 = ', np.dot(C[1,:],C[2,:]), '\n\n', 
     'Here, the rows of ONLY matrix B are orthogonal to each other.\n')
print('6. A^-1 is\n', ansB6a, '\n\nB^-1 is\n', ansB6b, '\n')
print('7. C^-1 is\n', ansB7, '\n')
print('8. The porduct of Ad is\n', ansB8, '\n')
print('9. The projection of the rows of A onto the vector d are\n', round(ansB9a.item(0)), ',', round(ansB9b.item(0)), 'and', round(ansB9c.item(0)), '\n')
print('10. column1 *', ansB10.item(0), 'column2 *', ansB10.item(1), 'column3 *', ansB10.item(2), '\n')
print('11. The solution x for the equation is\n', ansB11, '\n')
print('12. The solution x for the equation is\n', ansB12, '\nBecause the matrix C is a non invertible matrix or singular matrix.')

1. [[ 1  2  5]
 [ 6 -5 10]
 [-3 12 -3]] 

2. AB is
 [[ 14  -2  -4]
 [  9   0  15]
 [  7   7 -21]] 

 and BA is
 [[  9   3   8]
 [  6 -18  13]
 [ -5  15   2]] 

3. (AB)^T is
 [[ 14   9   7]
 [ -2   0   7]
 [ -4  15 -21]] 

 and B^T A^T is
 [[ 14   9   7]
 [ -2   0   7]
 [ -4  15 -21]] 

4. |A| is 55.0 and |B| is 0.0 

5. For two vectors to be orthogonal, their dot product has to be equal to 0.
 For matrix A, row1 (dot) row2 =  9 
 row1 (dot) row3 =  7 
 row2 (dot) row3 =  -13 

 For matrix B, row1 (dot) row2 =  0 
 row1 (dot) row3 =  0 
 row2 (dot) row3 =  0 

 For matrix C, row1 (dot) row2 =  32 
 row1 (dot) row3 =  10 
 row2 (dot) row3 =  19 

 Here, the rows of ONLY matrix B are orthogonal to each other.

6. A^-1 is
 [[-0.23636364  0.30909091  0.21818182]
 [ 0.07272727 -0.01818182  0.16363636]
 [ 0.36363636 -0.09090909 -0.18181818]] 

B^-1 is
 [[ 0.16666667  0.0952381   0.21428571]
 [ 0.33333333  0.04761905 -0.14285714]
 [ 0.16666667 -0.19047619  0.07142857]] 

7. C^-1 is
 [[ 1.20095

# Answer to the Question No. C

In [18]:
#Given

D = np.array([[1, 2], [3, 2]])
E = np.array([[2, -2], [-2, 5]])
F = np.array([[1, 2], [2, 4]])

In [19]:
#Solutions

ansC1 = np.linalg.eig(D)
ansC2 = np.matmul(ansC1[1][0],ansC1[1][1])
ansC3 = np.matmul(np.linalg.eig(E)[1][0], np.linalg.eig(E)[1][1])
ansC5 = np.linalg.lstsq(F, np.zeros((F.shape[0],1)), rcond=None)[0]
ansC6 = np.linalg.eig(F)[1]
ansC7 = np.linalg.lstsq(F, np.zeros((F.shape[0],1)), rcond=None)[0]

In [20]:
print('1. The eigenvalues of D are ', ansC1[0].item(0), 'and', ansC1[0].item(1))
print('And the eigenvectors of D are', ansC1[1][0], 'and', ansC1[1][1], '\n')
print('2. The dot product between the eigenvectors of D is', ansC2, '\n')
print('3. The dot product between the eigenvectors of E is', ansC3, '\n')
print('4. Since the dot product of the eigenvectors of E is 0, they are orthogonal.\n')
print('5. The trivial solution is\n', ansC5, '\n')
print('6. The two non trivial solutions x are\n', ansC6, '\n')
print('7. The solution is\n', ansC7, '\nAs the determinant of D is non-zero, the homogenous system of linear equations must have a unique (trivial) solution.')

1. The eigenvalues of D are  -1.0 and 4.0
And the eigenvectors of D are [-0.70710678 -0.5547002 ] and [ 0.70710678 -0.83205029] 

2. The dot product between the eigenvectors of D is -0.038461538461538214 

3. The dot product between the eigenvectors of E is 0.0 

4. Since the dot product of the eigenvectors of E is 0, they are orthogonal.

5. The trivial solution is
 [[0.]
 [0.]] 

6. The two non trivial solutions x are
 [[-0.89442719 -0.4472136 ]
 [ 0.4472136  -0.89442719]] 

7. The solution is
 [[0.]
 [0.]] 
As the determinant of D is non-zero, the homogenous system of linear equations must have a unique (trivial) solution.
